server:
    port: ${CLOUDINARY_UPLOAD_PORT:8084}
    servlet:
        context-path: /cloudinary

spring:
  application:
    name: cloudinary-upload

  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:10MB}
      max-request-size: ${CLOUDINARY_MAX_REQUEST_SIZE:10MB}

cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME:}
  api_key: ${CLOUDINARY_API_KEY:}
  api_secret: ${CLOUDINARY_API_SECRET:}


