server:
  port: ${NOTIFICATION_SERVICE_PORT:8082}
  servlet:
    context-path: /notification
spring:
  application:
    name: notification-service
  autoconfigure:
    exclude:   # Bỏ qua cấu hình MongoDB tự động
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
#  data:
#    mongodb:
#      uri: mongodb://root:root@localhost:27017/notification-service?authSource=admin
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    consumer:
      group-id: ${NOTIFICATION_KAFKA_GROUP_ID:notification-group}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
notification:
  email:
    brevo-url: ${BREVO_URL:https://api.brevo.com}
    brevo-apikey: ${BREVO_API_KEY:}
