server:
  port: ${API_GATEWAY_PORT:8888}

app:
  api-prefix: ${API_PREFIX:/nexus/v1}
  strip-prefix: ${API_GATEWAY_STRIP_PREFIX:2}
  cache:
    introspection-ttl-seconds: ${GATEWAY_INTROSPECTION_CACHE_TTL_SECONDS:30}

spring:
  application:
    name: api-gateway
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
  cloud:
    gateway:
      routes:
        - id: authentication_service
          uri: ${AUTHENTICATION_SERVICE_BASE_URL:http://authentication-service:8080}
          predicates:
          - Path=${app.api-prefix}/authentication/**
          filters:
          - StripPrefix=${app.strip-prefix}

        - id: profile_service
          uri: ${PROFILE_SERVICE_BASE_URL:http://profile-service:8081}
          predicates:
          - Path=${app.api-prefix}/profile/**
          filters:
          - StripPrefix=${app.strip-prefix}

        - id: post_service
          uri: ${POST_SERVICE_BASE_URL:http://post-service:8083}
          predicates:
            - Path=${app.api-prefix}/post/**
          filters:
            - StripPrefix=${app.strip-prefix}

        - id: chat_service
          uri: ${CHAT_SERVICE_BASE_URL:http://chat-service:8085}
          predicates:
            - Path=${app.api-prefix}/chat/**
          filters:
            - StripPrefix=${app.strip-prefix}
