server:
  port: ${POST_SERVICE_PORT:8083}
  servlet:
    context-path: /post
spring:
  application:
    name: post-service
  data:
    mongodb:
      uri: ${POST_MONGODB_URI:mongodb://root:root@mongodb:27017/post-service?authSource=admin}
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:10MB}
      max-request-size: ${MAX_REQUEST_SIZE:20MB}
file:
  max-size-mb: ${FILE_MAX_SIZE_MB:10}
  max-request-size: ${FILE_MAX_REQUEST_SIZE:20}

app:
  services:
    profile:
      url: ${PROFILE_SERVICE_URL:http://profile-service:8081/profile}
    cloudinary:
      url: ${CLOUDINARY_UPLOAD_URL:http://cloudinary-upload:8084/cloudinary}
