server:
  port: ${CHAT_SERVICE_PORT:8085}
  servlet:
    context-path: /chat
spring:
  application:
    name: chat-service
  data:
    mongodb:
      uri: ${CHAT_MONGODB_URI:mongodb://root:root@mongodb:27017/chat-service?authSource=admin}
      auto-index-creation: true
app:
  services:
    profile:
      url: ${PROFILE_SERVICE_URL:http://profile-service:8081/profile}
    authentication:
      url: ${AUTHENTICATION_SERVICE_URL:http://authentication-service:8080/authentication}
